# Generated by Django 4.2 on 2023-04-10 18:01

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.TextField(max_length=100)),
                ('difficulty', models.CharField(max_length=1, validators=[api.models.validate_difficulty])),
                ('description', models.TextField(max_length=1000)),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipments')),
            ],
        ),
        migrations.CreateModel(
            name='Muscles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(validators=[api.models.validate_age])),
                ('height', models.IntegerField(validators=[api.models.validate_height])),
                ('weight', models.IntegerField(validators=[api.models.validate_weight])),
                ('experience', models.CharField(max_length=1, validators=[api.models.validate_difficulty])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Workout_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exercises')),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workouts')),
            ],
        ),
        migrations.CreateModel(
            name='Gyms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.TextField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('is_shared', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Gym_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[api.models.validate_quantity])),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipments')),
                ('gym_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gyms')),
            ],
        ),
        migrations.AddField(
            model_name='exercises',
            name='muscle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.muscles'),
        ),
    ]
