# Generated by Django 4.2 on 2023-04-14 10:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_basic_data6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(blank=True, validators=[api.models.validate_age]),
        ),
        migrations.AlterField(
            model_name='users',
            name='experience',
            field=models.CharField(blank=True, max_length=1, validators=[api.models.validate_difficulty]),
        ),
        migrations.AlterField(
            model_name='users',
            name='height',
            field=models.IntegerField(blank=True, validators=[api.models.validate_height]),
        ),
        migrations.AlterField(
            model_name='users',
            name='weight',
            field=models.IntegerField(blank=True, validators=[api.models.validate_weight]),
        ),
    ]
