# Generated by Django 4.2 on 2023-04-14 10:12

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_users_age_alter_users_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(null=True, validators=[api.models.validate_age]),
        ),
        migrations.AlterField(
            model_name='users',
            name='experience',
            field=models.CharField(max_length=1, null=True, validators=[api.models.validate_difficulty]),
        ),
        migrations.AlterField(
            model_name='users',
            name='height',
            field=models.IntegerField(null=True, validators=[api.models.validate_height]),
        ),
        migrations.AlterField(
            model_name='users',
            name='weight',
            field=models.IntegerField(null=True, validators=[api.models.validate_weight]),
        ),
    ]
