# Generated by Django 4.2 on 2023-04-25 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_users_age_alter_users_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='gym_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.gyms'),
        ),
        migrations.AddField(
            model_name='workouts',
            name='muscle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.muscles'),
        ),
    ]
