# Generated by Django 4.2 on 2023-05-09 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_workouts_gym_id_workouts_muscle_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shared_gyms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gyms')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
