# Generated by Django 4.2 on 2023-05-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_shared_gyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout_details',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
